# Generated by Django 2.0.2 on 2018-02-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
