# Generated by Django 2.0.2 on 2018-02-22 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_remove_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='장르'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='멜론 Song ID'),
        ),
    ]
